apiVersion: v1
kind: Service
metadata:
  name: interview-app-svc
  namespace: default
spec:
  selector:
    app: interview-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
